'use client'; import {useEffect,useState} from 'react';
export default function Admin(){const [auth,setAuth]=useState(false),[login,setLogin]=useState({email:'',password:''}),[cfg,setCfg]=useState(null),[guests,setGuests]=useState([]),[wishes,setWishes]=useState([]),[newGuest,setNewGuest]=useState(''),[msg,setMsg]=useState('');
async function load(){let r=await fetch('/api/admin/config');if(r.ok){setAuth(true);setCfg((await r.json()).config);let g=await fetch('/api/admin/guests');if(g.ok)setGuests((await g.json()).guests);let w=await fetch('/api/admin/wishes');if(w.ok)setWishes((await w.json()).wishes)}}useEffect(()=>{load()},[]);
async function doLogin(e){e.preventDefault();let r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});if(r.ok){setMsg('Login berhasil');load()}else setMsg((await r.json()).error||'Gagal login')}
async function save(){let r=await fetch('/api/admin/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});setMsg(r.ok?'Tersimpan ✓':'Gagal menyimpan')}
async function addGuest(){if(!newGuest.trim())return;await fetch('/api/admin/guests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:newGuest})});setNewGuest('');load()}
if(!auth)return <main style={{maxWidth:420,margin:'50px auto',padding:20,fontFamily:'Arial'}}><h1>Admin Undangan</h1><form onSubmit={doLogin}><input style={S} placeholder="Email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input style={S} type="password" placeholder="Password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button style={B}>LOGIN</button></form><p>{msg}</p></main>;
return <main style={{maxWidth:850,margin:'20px auto',padding:20,fontFamily:'Arial'}}><h1>Admin Undangan 💙</h1><p>{msg}</p>{cfg&&<><h2>Data Undangan</h2><div style={grid}>{[['groom','Nama Pria'],['bride','Nama Wanita'],['dateLabel','Tanggal'],['venue','Tempat'],['address','Alamat'],['maps','Google Maps'],['groomFull','Nama Lengkap Pria'],['brideFull','Nama Lengkap Wanita'],['groomParents','Orang Tua Pria'],['brideParents','Orang Tua Wanita'],['akad','Jam Akad'],['reception','Jam Resepsi'],['musicUrl','URL Musik'],['musicTitle','Judul Musik'],['musicArtist','Artis Musik'],['photoGroom','URL Foto Pria'],['photoBride','URL Foto Wanita']].map(([k,l])=><label key={k}>{l}<input style={S} value={cfg[k]||''} onChange={e=>setCfg({...cfg,[k]:e.target.value})}/></label>)}</div><label>Quote<textarea style={{...S,height:100}} value={cfg.quote||''} onChange={e=>setCfg({...cfg,quote:e.target.value})}/></label><h3>Love Story</h3>{(cfg.story||[]).map((x,i)=><div key={i} style={grid}><input style={S} value={x[0]} onChange={e=>{let a=[...cfg.story];a[i]=[e.target.value,a[i][1]];setCfg({...cfg,story:a})}}/><input style={S} value={x[1]} onChange={e=>{let a=[...cfg.story];a[i]=[a[i][0],e.target.value];setCfg({...cfg,story:a})}}/></div>)}<button style={B} onClick={save}>SIMPAN PERUBAHAN</button></>}
<hr/><h2>Daftar Tamu</h2><input style={S} placeholder="Nama tamu" value={newGuest} onChange={e=>setNewGuest(e.target.value)}/><button style={B} onClick={addGuest}>TAMBAH</button>{guests.map(g=><div key={g.id} style={row}><b>{g.name}</b><span>/?to={encodeURIComponent(g.name)}</span><button onClick={async()=>{await fetch('/api/admin/guests?id='+g.id,{method:'DELETE'});load()}}>Hapus</button></div>)}<hr/><h2>Ucapan</h2>{wishes.map(w=><div style={row} key={w.id}><span><b>{w.name}</b> · {w.attendance}<br/>{w.message}</span><button onClick={async()=>{await fetch('/api/admin/wishes?id='+w.id,{method:'DELETE'});load()}}>Hapus</button></div>)}</main>}
const S={display:'block',width:'100%',padding:10,margin:'5px 0 12px',border:'1px solid #ddd',borderRadius:8};const B={padding:'11px 18px',background:'#78aede',color:'#fff',border:0,borderRadius:8,cursor:'pointer'};const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10};const row={display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',padding:10,borderBottom:'1px solid #eee'};
