'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
const fallback={groom:'Jaka',bride:'Dian',date:'2026-12-26T09:00:00+07:00',dateLabel:'26 DESEMBER 2026',venue:'Gedung Harmoni',address:'Jl. Melati No. 123, Jakarta',maps:'https://maps.google.com',groomFull:'Jaka Abdul Rizky',brideFull:'Dian',groomParents:'Putra Bapak Herman & Ibu Yuli',brideParents:'Putri Bapak & Ibu',akad:'08.00 – 10.00 WIB',reception:'11.00 – 14.00 WIB',quote:'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan hidup dari jenismu sendiri, supaya kamu mendapat ketenangan hati dan dijadikan-Nya kasih sayang di antara kamu.',story:[['Awal Pertemuan','Semua berawal dari sebuah pertemuan sederhana yang kemudian menjadi cerita indah.'],['Momen Bahagia','Waktu membuat kami semakin dekat hingga akhirnya memilih untuk berjalan bersama.'],['Selamanya','Dengan penuh syukur, kami memilih untuk melangkah bersama.']],banks:[],photos:[],musicUrl:'/assets/music.mp3',musicTitle:'Our Wedding Song',musicArtist:'Jaka & Dian'};
function Countdown({date}){const [left,setLeft]=useState('');useEffect(()=>{const tick=()=>{const d=new Date(date)-Date.now();if(d<=0){setLeft('Hari bahagia telah tiba ♡');return}const days=Math.floor(d/86400000),h=Math.floor(d/3600000)%24,m=Math.floor(d/60000)%60,sec=Math.floor(d/1000)%60;setLeft(`${days} Hari · ${h} Jam · ${m} Menit · ${sec} Detik`)};tick();const t=setInterval(tick,1000);return()=>clearInterval(t)},[date]);return <div className="card" style={{marginBottom:20}}><div className="caveat blue" style={{fontSize:30}}>Countdown</div><div style={{fontWeight:600}}>{left}</div></div>}
function Calendar(){let cells=[];for(let i=0;i<31;i++){let n=i+1;cells.push(<div key={n} className={n===26?'selected':''}>{n}</div>)}return <div className="calendar">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><div key={x} style={{fontWeight:600}}>{x}</div>)}{cells}</div>}
export default function Home(){const [cfg,setCfg]=useState(fallback),[open,setOpen]=useState(false),[playing,setPlaying]=useState(false),[wishes,setWishes]=useState([]),[form,setForm]=useState({name:'',message:'',attendance:'Hadir'});const audio=useRef(null);const guest=useMemo(()=>new URLSearchParams(typeof window!=='undefined'?window.location.search:'').get('to')||'',[]);
useEffect(()=>{fetch('/api/public').then(r=>r.ok?r.json():null).then(d=>d?.config&&setCfg(d.config)).catch(()=>{}); if(guest)setForm(f=>({...f,name:guest}))},[guest]);
function start(){setOpen(true);setTimeout(()=>{window.scrollTo(0,0);audio.current?.play().then(()=>setPlaying(true)).catch(()=>{})},650)}
function toggle(){if(!audio.current)return;if(audio.current.paused)audio.current.play().then(()=>setPlaying(true));else{audio.current.pause();setPlaying(false)}}
async function send(e){e.preventDefault();if(!form.message.trim())return;let r=await fetch('/api/wishes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,guest:guest||null})});if(r.ok){setForm(f=>({...f,message:''}));alert('Terima kasih, ucapan sudah terkirim.')}}
return <div className="page"><section className={'screen cover '+(open?'coverOut':'')} style={{display:open?'none':'flex'}}><div className="bow"><i/><span/><em/></div><div className="kicker blue caveat">THESE COUPLE ARE</div><h1 className="title blue caveat">Getting Married</h1><div className="date blue">{cfg.dateLabel}</div><div className="couple"><div className="person left"><div className="head"/><div className="bouquet">♥ ♡</div></div><div className="person right"><div className="head"/><div className="veil"/></div></div><div className="names blue caveat" style={{fontSize:34,marginBottom:16}}>{cfg.groom} &amp; {cfg.bride}</div><button className="open" onClick={start}>OPEN</button><div className="heart blue h1">♡</div><div className="heart pink h2">♥</div><div className="heart blue h3">♡</div><div className="heart pink h4">♥</div></section>
<div className={open?'mainIn':''} style={{display:open?'block':'none'}}><section className="screen hero2"><div className="mini blue caveat">The Wedding of</div><h1 className="names blue caveat">{cfg.groom}<br/>&amp; {cfg.bride}</h1><div className="quote">{cfg.quote}</div><div className="player"><div className="line"/><div className="controls"><span>↶</span><button className="play" onClick={toggle}>{playing?'Ⅱ':'▶'}</button><span>↷</span></div><div className="music-note">{cfg.musicTitle} · {cfg.musicArtist}</div></div><div style={{marginTop:'auto',width:'100%',height:190,position:'relative'}}><div style={{position:'absolute',left:'12%',bottom:25,width:110,height:120,borderLeft:'3px solid #8dc2e8',borderRadius:'50% 0 0 0',transform:'rotate(-8deg)'}}/><div style={{position:'absolute',right:'12%',bottom:25,width:110,height:120,borderRight:'3px solid #8dc2e8',borderRadius:'0 50% 0 0',transform:'rotate(8deg)'}}/><div className="caveat blue" style={{textAlign:'center',fontSize:30,paddingTop:90}}>♡</div></div></section>
<section className="screen section"><h2 className="blue caveat">Bride &amp; Groom</h2><div className="blue-line"/><div className="cards"><div className="card"><div className="photo">{cfg.photoGroom?<img src={cfg.photoGroom} alt="Mempelai pria"/>:'FOTO PRIA'}</div><h3 className="pink caveat" style={{fontSize:31,margin:8}}>{cfg.groom}</h3><div>{cfg.groomFull}</div><small>{cfg.groomParents}</small></div><div className="caveat blue" style={{fontSize:35,textAlign:'center'}}>&amp;</div><div className="card"><div className="photo">{cfg.photoBride?<img src={cfg.photoBride} alt="Mempelai wanita"/>:'FOTO WANITA'}</div><h3 className="pink caveat" style={{fontSize:31,margin:8}}>{cfg.bride}</h3><div>{cfg.brideFull}</div><small>{cfg.brideParents}</small></div></div></section>
<section className="screen section"><h2 className="blue caveat">Save The Date</h2><div className="blue-line"/><Countdown date={cfg.date}/><div className="card"><Calendar/><h3 className="pink caveat" style={{fontSize:30}}>Akad Nikah</h3><p>Sabtu, 26 Desember 2026<br/>{cfg.akad}</p><p>{cfg.venue}<br/>{cfg.address}</p><hr/><h3 className="pink caveat" style={{fontSize:30}}>Resepsi</h3><p>{cfg.reception}</p><a className="btn" href={cfg.maps} target="_blank">Lihat Lokasi</a></div></section>
<section className="screen section"><h2 className="blue caveat">Our Love Story</h2><div className="blue-line"/><div className="timeline">{(cfg.story||[]).map(([a,b])=><div className="story" key={a}><b className="pink">{a}</b><p>{b}</p></div>)}</div></section>
<section className="screen section"><h2 className="blue caveat">Wedding Gift</h2><div className="blue-line"/><p>Doa dan restu adalah hadiah terindah. Bagi yang ingin berbagi tanda kasih:</p>{(cfg.banks||[]).map((b,i)=><div className="gift" style={{marginBottom:12}} key={i}><b>{b.bank}</b><h3 style={{margin:8}}>{b.account}</h3><div>{b.owner}</div><button className="btn" onClick={()=>navigator.clipboard?.writeText(b.account)}>Salin</button></div>)}</section>
<section className="screen section"><h2 className="blue caveat">Love Your Wishes!</h2><div className="blue-line"/><form className="card" onSubmit={send}><h3 className="blue caveat" style={{fontSize:26}}>💌 Kirim Ucapan &amp; Doa</h3><input className="field" placeholder="Nama kamu" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea className="field" rows="4" placeholder="Ucapan & doa" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><select className="field" value={form.attendance} onChange={e=>setForm({...form,attendance:e.target.value})}><option value="Hadir">Berkenan hadir</option><option value="Tidak hadir">Maaf tidak bisa hadir</option></select><button className="submit">♡ Kirim</button></form>{wishes.map((x,i)=><div className="wish" key={i}><b>{x.name}</b> · {x.attendance}<br/>{x.message}</div>)}</section><footer className="footer"><h2 className="blue caveat">See You at Our Wedding Day!</h2><p className="pink caveat" style={{fontSize:25}}>With Love<br/>{cfg.groom} &amp; {cfg.bride}</p></footer></div><audio ref={audio} src={cfg.musicUrl||'/assets/music.mp3'} preload="auto" loop/><button onClick={toggle} className={'music-float '+(playing?'spin':'')} style={{display:open?'block':'none'}}>♪</button></div>}
